// Build the "complete framework" JS file the user can download at the end
// of the course. It concatenates each step's canonical solution with the
// platform-provided hostCode for that step, in step-id order, producing a
// single self-contained file that mirrors what un-React looks like once
// all steps are implemented correctly.
//
// We ship the *canonical* solution rather than the user's in-progress code
// — the user's buffer may not even compile, and "framework code" implies
// the reference answer.

import type { Step } from '../types';

export function buildFrameworkCode(steps: Step[]): string {
  const sorted = [...steps].sort((a, b) => a.id.localeCompare(b.id));
  const header = [
    '// un-React — your build, assembled.',
    '// Generated by the un-React platform on ' + new Date().toISOString().slice(0, 10) + '.',
    '//',
    '// This is the canonical reference implementation built up over the',
    '// curriculum, in step order. Drop it into a page with a <div id="root">',
    '// and any JSX transpiled with the UnReact.createElement pragma will',
    '// render through it.',
    '',
  ];
  const sections = sorted.map((s) => [
    `// ─────────────────────────────────────────────────────────────────`,
    `// ${s.id.toUpperCase()} — ${s.title}`,
    `// ─────────────────────────────────────────────────────────────────`,
    s.solution.trim(),
    '',
    '// ' + s.id + ' — platform-provided helpers',
    s.hostCode.trim(),
    '',
  ].join('\n'));
  return header.join('\n') + '\n' + sections.join('\n');
}

export function downloadText(filename: string, body: string): void {
  const blob = new Blob([body], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke a tick later so the browser has had a chance to read it.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
